services:
  db:
    container_name: cyber-sec-database
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: node
      POSTGRES_PASSWORD: node
      POSTGRES_DB: cyber-sec-database
    ports:
      - 5432:5432
    networks:
      - cyber-sec
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - cyber-sec
  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: cyber-sec@cyber-sec.com
      PGADMIN_DEFAULT_PASSWORD: cyber-sec
    networks:
      - cyber-sec

networks:
  cyber-sec:
    external: true