services:
  db:
    container_name: cyber-sec-database
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - cyber-sec
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - cyber-sec
    volumes:
      - db-data:/var/lib/postgresql/data
    tmpfs:
      - /tmp
    read_only: true
    security_opt:
      - no-new-privileges:true
  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - cyber-sec
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - cyber-sec
    volumes:
      - mongo-data:/data/db
networks:
  cyber-sec:
    external: true

volumes:
  db-data:
  mongo-data: